import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";

import { verifyClaimToken } from "@/lib/api/auth";

// Landing point for the verification link generated by the domain-match
// claim path (see Register.jsx's VerifyStep and routes/businesses.js POST
// /claim). Consuming the token here — rather than at generation time — is
// what stands in for "the claimant was able to open their company inbox
// and click through," since only someone with access to that address
// could have reached this URL.
function VerifyClaimLink() {
  const { token } = useParams();
  const [status, setStatus] = useState("verifying");
  const [error, setError] = useState(null);
  const ran = useRef(false);

  useEffect(() => {
    if (ran.current) return;
    ran.current = true;

    verifyClaimToken(token)
      .then(() => setStatus("done"))
      .catch((err) => {
        setError(err.message);
        setStatus("error");
      });
  }, [token]);

  if (status === "verifying") {
    return (
      <div className="mx-auto max-w-[520px] px-6 py-24 text-center">
        <p className="text-sm text-grey-600 dark:text-muted-foreground">
          Verifying your email…
        </p>
      </div>
    );
  }

  if (status === "error") {
    return (
      <div className="mx-auto max-w-[520px] px-6 py-24 text-center">
        <h1 className="text-xl font-extrabold text-ink dark:text-foreground">
          Verification failed
        </h1>
        <p className="mt-2 text-sm text-grey-600 dark:text-muted-foreground">{error}</p>
        <Link
          to="/register"
          className="mt-6 inline-block text-sm font-bold text-ink underline-offset-2 hover:underline dark:text-foreground"
        >
          Start your claim again
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-[520px] px-6 py-24 text-center">
      <h1 className="text-xl font-extrabold text-ink dark:text-foreground">
        Your business is claimed
      </h1>
      <p className="mt-2 text-sm text-grey-600 dark:text-muted-foreground">
        Your email is verified and the claim is approved. Log in to continue to your
        dashboard.
      </p>
      <Link
        to="/login"
        className="mt-6 inline-flex items-center gap-2 rounded-sm border border-transparent bg-yellow px-5 py-2.5 text-[14px] font-bold text-yellow-ink transition-all hover:-translate-y-px hover:bg-yellow-hi hover:shadow-md"
      >
        Go to login
      </Link>
    </div>
  );
}

export { VerifyClaimLink };
