import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { verifyClaimToken } from "@/lib/api/auth";
import { useAuth } from "@/context/AuthContext";

// Landing point for the verification link generated by the domain-match
// claim path (see Register.jsx's VerifyStep and routes/businesses.js POST
// /claim). Consuming the token here — rather than at generation time — is
// what stands in for "the claimant was able to open their company inbox
// and click through," since only someone with access to that address
// could have reached this URL.
function VerifyClaimLink() {
  const { token } = useParams();
  const navigate = useNavigate();
  const { refreshAccount } = useAuth();
  const [status, setStatus] = useState("verifying");
  const [error, setError] = useState(null);
  const ran = useRef(false);

  useEffect(() => {
    if (ran.current) return;
    ran.current = true;

    verifyClaimToken(token)
      // The backend set a session cookie while consuming the token, so by
      // now they ARE logged in — AuthContext just doesn't know it, having
      // fetched /auth/me before any of this happened. Without the refresh
      // the app sends an already-authenticated user to a login form, and
      // (for a tap-driven registration) hides the connection they just
      // made from the only page that would show it.
      .then(async () => {
        await refreshAccount();
        setStatus("done");
        navigate("/app", { replace: true });
      })
      .catch((err) => {
        setError(err.message);
        setStatus("error");
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token]);

  if (status === "verifying") {
    return (
      <div className="mx-auto max-w-[520px] px-6 py-24 text-center">
        <p className="text-sm text-grey-600 dark:text-muted-foreground">
          Verifying your email…
        </p>
      </div>
    );
  }

  if (status === "error") {
    return (
      <div className="mx-auto max-w-[520px] px-6 py-24 text-center">
        <h1 className="text-xl font-extrabold text-ink dark:text-foreground">
          Verification failed
        </h1>
        <p className="mt-2 text-sm text-grey-600 dark:text-muted-foreground">{error}</p>
        <Link
          to="/register"
          className="mt-6 inline-block text-sm font-bold text-ink underline-offset-2 hover:underline dark:text-foreground"
        >
          Start your claim again
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-[520px] px-6 py-24 text-center">
      <h1 className="text-xl font-extrabold text-ink dark:text-foreground">
        Your business is claimed
      </h1>
      <p className="mt-2 text-sm text-grey-600 dark:text-muted-foreground">
        Your email is verified and the claim is approved. Taking you to your dashboard…
      </p>
      {/* The effect above redirects, so this is only ever a brief flash — it
          stays as a way through if that navigation doesn't happen. */}
      <Link
        to="/app"
        className="mt-6 inline-flex items-center gap-2 rounded-sm border border-transparent bg-yellow px-5 py-2.5 text-[14px] font-bold text-yellow-ink transition-all hover:-translate-y-px hover:bg-yellow-hi hover:shadow-md"
      >
        Go to your dashboard
      </Link>
    </div>
  );
}

export { VerifyClaimLink };
